CB-27079 - Cluster side: Place nginx configs into the secret storage - Public cert
hortonworks/cloudbreak-images pull request #1045
Opened 2024-09-12 10:23 UTC by gregito

2024-09-24 13:06 UTC, lajosrodek requested changes

2024-09-24 13:06 UTC, lajosrodek commented on saltstack/base/salt/luks/bin/populate-luks-volume.sh
> +    fi
This is wrong, the `/etc/certs` is also applicable to FreeIPA. Perhaps it makes more sense to put the `if [[ "$IS_FREEIPA" != "true" ]]` check around the `process_location_with_create "/etc/certs-user-facing"` invocation above.

2024-10-01 15:32 UTC, lajosrodek approved these changes
Thanks, LGTM

2024-10-22 08:01 UTC, TheTinkerDad approved these changes

2024-10-22 12:42 UTC, merged