CB-27090 - Produce dedicated log files for secret encryption scripts
hortonworks/cloudbreak-images pull request #1047
Opened 2024-09-16 09:21 UTC by gregito

2024-10-01 16:15 UTC, lajosrodek requested changes
Two minor asks.

2024-10-02 08:12 UTC, gregito commented on saltstack/base/salt/luks/etc/systemd/system/cdp-reopen-luks-volume.service
> +ExecStart=/bin/bash -c '/etc/cdp-luks/bin/reopen-luks-volume.sh | tee /var/log/cdp-luks/reopen-luks-volume-$(date +%s).log'
thank you! :)

2024-10-03 12:23 UTC, lajosrodek approved these changes
Thanks, LGTM

2024-10-04 11:35 UTC, lajosrodek requested changes
Sorry, a few more asks.

2024-10-04 11:35 UTC, lajosrodek commented on saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
>    echo "LUKS volume population with secrets finished."
Sorry, forgot mentioning that we should think about the `${PIPESTATUS[0]}` thing in these script executions as well. There are two choices: either `exit` explicitly abort if `${PIPESTATUS[0]}` is nonzero, or just `return` from the function with the nonzero `${PIPESTATUS[0]}`. As I see, https://github.infra.cloudera.com/cloudbreak/cloudbreak/pull/2733 / [CB-27096](https://jira.cloudera.com/browse/CB-27096) will force `user-data-helper.sh` abort if any command execution fails, so even the `return` option is satisfactory.

2024-10-22 12:43 UTC, TheTinkerDad approved these changes

2024-10-22 12:43 UTC, merged