CDPAM-1403 | Add logrotate conf to enable log rotation for ccmv2 agent logs
hortonworks/cloudbreak-images pull request #542
Opened 2021-03-22 13:30 UTC by SachinHg

In this PR I have added a logrotate configuration file for ccmv2-inverting-proxy-agent's log to rotate the log every 6 days or when the size is 128MB. The `init.sls` script is updated to trigger this logrotate policy as well.
The configuration follows the rules for https://github.com/hortonworks/cloudbreak/blob/master/freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/ipabackup.

2021-03-22 15:18 UTC, lacikaaa commented on saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls
> +  file.managed"
`"` doesn't look right

2021-03-22 15:20 UTC, lacikaaa requested changes

2021-03-22 15:20 UTC, lacikaaa commented on saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls
> +  file.managed"
`"` doesn't look right

2021-03-22 15:20 UTC, lacikaaa commented on saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls
> +    -mode: 644
missing space

2021-03-23 06:15 UTC, SachinHg commented on saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls
> +    -mode: 644
sorry. My laptop's keyboard has some issues :\

2021-03-23 06:19 UTC, SachinHg commented on saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls
> +  file.managed"
fixed

2021-03-23 11:48 UTC, zabhi approved these changes

2021-03-23 13:13 UTC, biharitomi approved these changes

2021-03-23 14:44 UTC, lacikaaa approved these changes
LGTM
please test it by following this: https://cloudera.atlassian.net/wiki/spaces/ENG/pages/1283916646/How+to+burn+new+prewarmed+image+for+testing+purposes

2021-03-24 04:29 UTC, SachinHg commented
@lacikaaa I triggered the job http://build.eng.hortonworks.com:8080/job/cloudbreak-image-burn-salt-v3/16176/ which succeeded. Could the changes be merged now?

2021-03-24 08:33 UTC, merged