CB-23499 Add hardening tag
hortonworks/cloudbreak-images pull request #905
Opened 2023-10-10 13:15 UTC by Bajzathd

2023-10-17 13:09 UTC, TheTinkerDad requested changes

2023-10-17 13:09 UTC, TheTinkerDad commented on saltstack/final/salt/metadata/tmp/generate-tags.sh
> +if [ "${CLOUD_PROVIDER}" != "AWS_GOV" ]; then
As part of CB-22247 we've already enabled CIS for Gov Cloud images as well - this "if" is no longer needed.

2023-10-19 09:37 UTC, pkedvessy approved these changes

2023-10-19 13:04 UTC, TheTinkerDad approved these changes

2023-10-19 13:25 UTC, merged